### ISSUE TITLE
RxBus depends on RxJava 2.x

### ISSUE THREAD

**Issue by tarek360** [Anadea/RxBus#1]
Hi,
I want to thank you for developing this library :)
I want to ask you, do you have another version depend on RxJava 1.x or another way to use it in my app which depends on RxJava 1.x?

**Comment by dubroff** [comment]
Hi,
we don't have version depend on RxJava 1.x. The library was originally based on the features RxJava 2.x.

**Comment by tarek360** [comment]
Is there any work around to use RxBus in projects depends on RxJava 1.x?

**Comment by dubroff** [comment]
Hi, you can jump to the [RxJava 1.x based branch](https://github.com/Anadea/RxBus/tree/Rx1xBus) and Import the library module to your project. Please note that we do not plan to publish the implementation based on RxJava v1.x. in MavenCentral.

**Comment by tarek360** [comment]
Thank you very much 👍
